# Generated by Django 5.0.12 on 2025-03-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"verbose_name_plural": "Job Applications"},
        ),
        migrations.AlterModelOptions(
            name="jobapplicationstatus",
            options={"verbose_name_plural": "Job Application Statuses"},
        ),
        migrations.AlterModelOptions(
            name="jobapplicationstatushistory",
            options={"verbose_name_plural": "Job Application Status History"},
        ),
    ]
