# Generated by Django 5.0.12 on 2025-03-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="job_application_id",
            new_name="application_id",
        ),
    ]
