# Generated by Django 5.0.12 on 2025-03-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_applications",
            "0004_rename_job_application_id_jobapplication_application_id",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-applied_at"],
                "verbose_name_plural": "Job Applications",
            },
        ),
    ]
