# Generated by Django 5.0.12 on 2025-03-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0006_alter_jobapplication_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplicationstatus",
            options={
                "ordering": ["status_code"],
                "verbose_name_plural": "Job Application Statuses",
            },
        ),
    ]
