# Generated by Django 5.0.12 on 2025-03-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_applications", "0007_alter_jobapplicationstatus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplicationstatushistory",
            options={
                "ordering": ["-changed_at"],
                "verbose_name_plural": "Job Application Status History",
            },
        ),
    ]
