# Generated by Django 5.0.12 on 2025-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("jobseeker", "Jobseeker"),
                    ("employer", "Employer"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
