# Generated by Django 5.0.12 on 2025-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("jobseeker", "Jobseeker"),
                    ("employer", "Employer"),
                ],
                max_length=50,
            ),
        ),
    ]
