# Generated by Django 5.0.12 on 2025-02-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
