# Generated by Django 5.0.12 on 2025-03-05 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "industry_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("part-time", "Part-time"),
                            ("full-time", "Full-time"),
                            ("remote", "Remote"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expiration_date", models.DateTimeField(db_index=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
                "ordering": ["-posted_at", "location", "industry"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "location_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Job Location",
                "verbose_name_plural": "Job Locations",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "skill_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
    ]
