# Generated by Django 5.0.12 on 2025-03-04 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["job_id"], name="job_listing_job_id_c947a1_idx"),
        ),
    ]
