# Generated by Django 5.0.12 on 2025-03-06 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job_listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_postings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="job_listings.industry",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["city"], name="job_listing_city_cd66de_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["country"], name="job_listing_country_f10fa0_idx"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="job_listings.location",
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills_required",
            field=models.ManyToManyField(
                blank=True, related_name="job_postings", to="job_listings.skill"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["job_id"], name="job_listing_job_id_c947a1_idx"),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["title"], name="job_listing_title_bf02ae_idx"),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["job_type"], name="job_listing_job_typ_4083cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["expiration_date"], name="job_listing_expirat_24d07b_idx"
            ),
        ),
    ]
