# Generated by Django 5.0.12 on 2025-03-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={
                "ordering": ["name"],
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["city", "country"],
                "verbose_name": "Job Location",
                "verbose_name_plural": "Job Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="job_listing_name_3d91fe_idx"),
        ),
    ]
