# Generated by Django 5.0.12 on 2025-03-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0002_jobposting_job_listing_job_id_c947a1_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name": "Industry", "verbose_name_plural": "Industries"},
        ),
        migrations.AlterModelOptions(
            name="jobposting",
            options={
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
            },
        ),
        migrations.AlterModelOptions(
            name="jobtype",
            options={"verbose_name": "Job Type", "verbose_name_plural": "Job Types"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Job Location",
                "verbose_name_plural": "Job Locations",
            },
        ),
    ]
