# Generated by Django 5.0.12 on 2025-03-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="state",
        ),
    ]
