# Generated by Django 5.0.12 on 2025-03-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0003_remove_location_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="skills_required",
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="industry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings",
                to="job_listings.industry",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_postings",
                to="job_listings.location",
            ),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills_required",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
