# Generated by Django 5.0.12 on 2025-03-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0003_alter_industry_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="location",
            name="job_listing_city_cd66de_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="job_listing_country_f10fa0_idx",
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["city", "country", "state_or_province", "postal_code"],
                name="job_listing_city_410469_idx",
            ),
        ),
    ]
