# Generated by Django 5.0.12 on 2025-03-04 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_listings",
            "0003_alter_industry_options_alter_jobposting_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="expiration_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("part-time", "Part-time"),
                    ("full-time", "Full-time"),
                    ("remote", "Remote"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="skills_required",
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["title"], name="job_listing_title_bf02ae_idx"),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["job_type"], name="job_listing_job_typ_4083cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["expiration_date"], name="job_listing_expirat_24d07b_idx"
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="skills_required",
            field=models.ManyToManyField(
                db_index=True, related_name="job_postings", to="job_listings.skill"
            ),
        ),
    ]
