# Generated by Django 5.0.12 on 2025-03-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0004_remove_jobposting_skills_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("part-time", "Part-time"),
                    ("full-time", "Full-time"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("remote", "Remote"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
