# Generated by Django 5.0.12 on 2025-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0004_skill_alter_jobposting_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobposting",
            options={
                "ordering": ["-posted_at", "location", "industry"],
                "verbose_name": "Job Posting",
                "verbose_name_plural": "Job Postings",
            },
        ),
    ]
