# Generated by Django 5.0.12 on 2025-03-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0005_alter_jobposting_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobType",
        ),
    ]
