# Generated by Django 5.0.12 on 2025-03-12 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_listings", "0005_jobposting_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="skills_required",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="job_postings",
                to="job_listings.skill",
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["industry"], name="job_listing_industr_5254d3_idx"
            ),
        ),
    ]
